### ISSUE TITLE
Integrate Multi-token URI scheme 

### ISSUE THREAD

**Issue by AdamBLevine** [tokenly/token-slot#1]
To enhance ease-of-use with LTB Companion and Token Pockets wallet, please integrate the following scheme when displaying addresses so users may more easily send tokens to each other and avoid sending tokens to addresses that do not know how to see or deal with them.

When a unique redemption address is generated, the expected-token-type, payment address and redemption invoice number (as data-label) should be populated automatically.

![image](https://cloud.githubusercontent.com/assets/6858319/7715618/2ec0ae76-fe3e-11e4-8d9a-4111cf14d3de.png)

The button should be located beside the fully visible payment address in the highlighted area pictured above.

Here is an example that would accept BTC or any other single token only, because TokenSlot gathers the specific type of token the user wishes to pay before generating the pay-to-address we will always be generating this type of single-token filter

`<span class="companion-tip-button" data-address="1Dhx3kGVkLaVFDYacZARheNzAWhYPTxHLq" data-label="bitcoin only" data-tokens="btc"></span>`

**Note: use all or no capitalization when describing date-tokens, LTBCOIN,FLDC,SJCX or ltbcoin,fldc,sjcx - mixed capitalization will not work.

**Comment by cryptonaut420** [comment]
closing this as it is on application level and also already implemented
