### ISSUE TITLE
Add "Tokens Accepted" API call for both text & symbol listings from Coincap.io

### ISSUE THREAD

**Issue by AdamBLevine** [tokenly/token-slot#5]
People would like to be able to display what tokens are being accepted without having to manually update the website whenever a change is made.  Allowing the current status, prices and token art to be called via our API would mean listings would never be out of date and as new tokens are accepted you'll visibly see that acceptance.

**Comment by cryptonaut420** [comment]
moved issue to Tend repository (Tend will have its own public API with basic information like this on public forms)
