### ISSUE TITLE
Add "Shopping Cart" mode

### ISSUE THREAD

**Issue by AdamBLevine** [tokenly/token-slot#6]
A user should be able to add multiple items sold by one vendor to a list that is kept track of by Token-slot, when they check out they should be presented with either

a. One 'bitsplit' address which routes payment to the appropriate invoices at each of the involved vendors.
b. a list of addresses and invoices they perform multiple payments to do direclty.

I think b is very attainable right now but "a" is by far the more elegant solution.   I believe we should strive for "a" with our first iteration.   Think Shopping cart as personal shopper automating all the deals and haggling and just handing you one simple bill at the end of the day.

**Comment by cryptonaut420** [comment]
this seems like something more on a front-end application level, e.g on Tend rather than a new ability in the backend API. closing for now
