### ISSUE TITLE
Add User Feedback & Basic Reputation System

### ISSUE THREAD

**Issue by AdamBLevine** [tokenly/token-slot#7]
It would be nice if Tokenslot handled email notifications communicating the various stages of an order that has multiple stages like something that is shipped and delivered.  
- The package must be tracked and that information must be provided to the user
- A user must be able to confirm they received their order successfully, report damage or failure and seek regress through an arbitration system.  I recommend judge.me's standard inclusion clause or whatever that one that Pamela Morgan is a adjudicator with.
- A user must be able to leave feedback on a merchant which should let them make notes about a transaction as well as ask them to answer several standard questions like.

We might just want to integrate a large part of Amazons API and not waste as much time reinventing this wheel ourselves, investigate that possibility.

**Comment by cryptonaut420** [comment]
moving this to be a feature for Tend
